#include "mbed.h"

#define INTEGRATOR_FLASH_SCLK  PC_10
#define INTEGRATOR_FLASH_MISO  PC_11
#define INTEGRATOR_FLASH_MOSI  PC_12

#define INTEGRATOR_FLASH0_CS1  PD_0
#define INTEGRATOR_FLASH1_CS2  PD_1